version: '2'
services:
  litemall-admin-api:
    image: registry.homelab.org/litemall-admin-api:0.1.0
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: application=true
  mysql:
    image: registry.homelab.org/litemall-mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: litemall123456
    volumes:
      - /litemall/mysql/data:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --default-authentication-plugin=mysql_native_password
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: application=true
  litemall-admin:
    image: registry.homelab.org/litemall-admin:0.1.0
    ports:
      - 9527:9527/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: application=true